-- Z3-Rando-Hud-Addresses
-- Accurate as of vt27
-- Addresses are from WRAM
-- WRAM addresses start at System Bus 0x7E0000

res = [[.\images\res\]]
blank = [[blank.png]]

heartPiece = {address=0xF36B, row=4, col=0, [0]=res .. "hp0.png", res .. "hp1.png", res .. "hp2.png", res .. "hp3.png"}

quiver = {address=0xF371, row=5, col=4, [0] = res .. blank}
bomb_bag = {address=0xF370, row=0, col=3, [0] = res .. blank}
bottle = {address=0xF35C, row=6, col=0, [0] = res .. blank}

pendants = {address=0xF374, row=0, col=5, poss={[0]=3,2,1,0,0,0,0,0}}
crystals = {address=0xF37A, row=0, col=6, poss={[0]=6,1,5,7,2,4,3,0}}

lwbosses = {offsets={[0]=0xC8,0x33,0x07}, row=4, col=5, poss={[0]=0,1,2}, img={[0]="EP","DP","ToH"}, keyDex={[0]=2,3,10}, compassByte={[0]=1,1,0}, compassBit={[0]=5,4,5}}
dwbosses = {offsets={[0]=0x5A,0x06,0x29,0xAC,0xDE,0x90,0xA4}, row=0, col=7, poss={[0]=0,1,2,3,4,5,6}, img={[0]="PoD","SP","SW","TT","IP","MM","TR"}, keyDex={[0]=6,5,8,11,9,7,12}, compassByte={[0]=1,1,0,0,0,1,0}, compassBit={[0]=1,2,7,4,6,0,3}}

boss_root_addr = 0xF001
boss_checkBit = 3

di_root_addr = 0xF364

OWUW_indic = 0x0B80
room_Index = 0x048E
ow_loc_dex = 0x040A

aga_state = {address={[0]=0xf041, 0xf01b}, row=3, col=0, keyDex={[0]=4,13}}

keys = {
	  [0] = 0xf37C, --  0 Sewer Passage
			0xf37D, --  1 Hyrule Castle
			0xf37E, --  2 Eastern Palace
			0xf37F, --  3 Desert Palace
			0xf380, --  4 Castle Tower
			0xf381, --  5 Swamp Palace
			0xF382, --  6 Dark Palace
			0xF383, --  7 Misery Mire
			0xF384, --  8 Skull Woods
			0xF385, --  9 Ice Palace
			0xF386, -- 10 Tower of Hera
			0xF387, -- 11 Gargoyle's Domain
			0xF388, -- 12 Turtle Rock
			0xf389, -- 13 Ganon's Tower
			0xf38A, -- 14 unused A
			0xf38B  -- 15 unused B
}

-- Y ITEMS ARRAY
ItemsArray = {
	bow = {address=0xF340, row=0, col=0, [0] = res .. blank, res .. "bow1.png", res .. "bow2.png", res .. "bow3.png", res .. "bow4.png"},
	boomerang = {address=0xF341, row=0, col=1, [0] = res .. blank, res .. "boom1.png", res .. "boom2.png"},
	hookshot = {address=0xF342, row=0, col=2,[0] = res .. blank, res .. "hookshot.png"},
	mushroom = {address=0xF344, row=0, col=4,[0] = res .. blank, res .. "mushroom.png", res .. "powder.png"},
	fire = {address=0xF345, row=1, col=0,[0] = res .. blank, res .. "fire.png"},
	ice = {address=0xF346, row=1, col=1,[0] = res .. blank, res .. "ice.png"},
	bombos = {address=0xF347, row=1, col=2,[0] = res .. blank, res .. "bombos.png"},
	ether = {address=0xF348, row=1, col=3,[0] = res .. blank, res .. "ether.png"},
	quake = {address=0xF349, row=1, col=4,[0] = res .. blank, res .. "quake.png"},
	lamp = {address=0xF34A, row=2, col=0,[0] = res .. blank, res .. "lamp.png"},
	hammer = {address=0xF34B,row=2, col=1, [0] = res .. blank, res .. "hammer.png"},
	shovel = {address=0xF34C,row=2, col=2, [0] = res .. blank, res .. "shovel.png", res .. "flute1.png", res .. "flute2.png"},
	net = {address=0xF34D,row=2, col=3, [0] = res .. blank, res .. "net.png"},
	book = {address=0xF34E,row=2, col=4, [0] = res .. blank, res .. "book.png"},
	somaria = {address=0xF350,row=3, col=1, [0] = res .. blank, res .. "somaria.png"},
	byrna = {address=0xF351,row=3, col=2, [0] = res .. blank, res .. "byrna.png"},
	cape = {address=0xF352,row=3, col=3, [0] = res .. blank, res .. "cape.png"},
	mirror = {address=0xF353,row=3, col=4, [0] = res .. blank, res .. "letter.png", res .. "mirror.png"},
	gloves = {address=0xF354,row=4, col=2, [0] = res .. blank, res .. "gloves1.png", res .. "gloves2.png"},
	boots = {address=0xF355,row=4, col=1, [0] = res .. blank, res .. "boots.png", res .. "boots.png"},
	flippers = {address=0xF356,row=4, col=3, [0] = res .. blank, res .. "flippers.png"},
	pearl = {address=0xF357,row=4, col=4, [0] = res .. blank, res .. "pearl.png"},
	sword = {address=0xF359,row=5, col=1, [0] = res .. blank, res .. "sword1.png", res .. "sword2.png", res .. "sword3.png", res .. "sword4.png"},
	shield = {address=0xF35A,row=5, col=2, [0] = res .. blank, res .. "shield1.png", res .. "shield2.png", res .. "shield3.png"},
	armor = {address=0xF35B,row=5, col=3, [0] = res .. "tunic0.png", res .. "tunic1.png", res .. "tunic2.png"},
	magic = {address=0xF37B,row=5, col=0, [0] = res .. "magic0.png", res .. "magic1.png", res .. "magic2.png"}
}

UnderworldList = {
[0]={name="GANON",dark=true},
	{name="Hyrule Castle 1F",dark=false},
	{name="The Escape",dark=false},
	{name="Houlihan Room",dark=false},
	{name="Turtle Rock B1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Swamp Colony - ARRGHUS",dark=false},
	{name="Tower Guardian - MOLDORM",dark=false},
	{name="River Fairy Fountain",dark=false},
	{name="Palace of Darkness B1F",dark=false},
	{name="Palace of Darkness B1F",dark=false},
	{name="Palace of Darkness B1F",dark=true},
	{name="Ganon's Tower 2F",dark=false},
	{name="Ganon's Puppet - AGAHNIM",dark=false},
	{name="Ice Palace 1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="The Hero's Downfall",dark=false},
	{name="The Escape",dark=false},
	{name="Sanctuary",dark=false},
	{name="Turtle Rock B1F",dark=false},
	{name="Turtle Rock B1F",dark=false},
	{name="Turtle Rock B1F",dark=false},
	{name="Swamp Palace B1F",dark=false},
	{name="Tower of Hera 5F",dark=false},
	{name="River Fairy Fountain",dark=false},
	{name="Palace of Darkness 1F",dark=true},
	{name="Palace of Darkness 1F",dark=false},
	{name="Palace of Darkness 1F",dark=false},
	{name="Ganon's Tower B1F",dark=false},
	{name="Ganon's Tower 7F",dark=false},
	{name="Ice Palace B1F",dark=false},
	{name="Ice Palace B1F",dark=false},
	{name="The Deceiver - AGAHNIM",dark=false},
	{name="The Escape",dark=true},
	{name="The Escape",dark=true},
	{name="Turtle Rock B1F (Assassin Eyes Entrance)",dark=false},
	{name="Turtle Rock B1F (Big Chest Entrance)",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Swamp Palace B1F",dark=false},
	{name="Tower of Hera 4F",dark=false},
	{name="Swamp Palace 1F",dark=false},
	{name="Forest Wraith - MOTHULA",dark=false},
	{name="Palace of Darkness 1F",dark=false},
	{name="Palace of Darkness 1F",dark=false},
	{name="Hookshot Cave (Back)",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Ice Palace B1F",dark=false},
	{name="Kakariko Well",dark=false},
	{name="Agahnim's Tower 7F",dark=false},
	{name="Tower of Hera 3F",dark=false},
	{name="The Escape",dark=true},
	{name="Desert Guardians - LANMOLAS",dark=false},
	{name="Swamp Palace B1F",dark=false},
	{name="Swamp Palace B1F",dark=false},
	{name="Swamp Palace B1F",dark=false},
	{name="Swamp Palace B1F",dark=false},
	{name="Swamp Palace B1F",dark=false},
	{name="Skull Woods 1F",dark=false},
	{name="Palace of Darkness 1F",dark=false},
	{name="Palace of Darkness B1F",dark=false},
	{name="Hookshot Cave (Front)",dark=false},
	{name="Ganon's Tower 6F",dark=false},
	{name="Ice Palace B2F",dark=false},
	{name="Ice Palace B2F",dark=false},
	{name="Agahnim's Tower 6F",dark=false},
	{name="The Escape",dark=true},
	{name="The Escape",dark=true},
	{name="Desert Palace 2F",dark=false},
	{name="Thieves' Town B2F",dark=false},
	{name="Thieves' Town B2F",dark=false},
	{name="Swamp Palace B1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Skull Woods 1F",dark=false},
	{name="Palace of Darkness 1F",dark=false},
	{name="Palace of Darkness B1F",dark=false},
	{name="Ganon's Tower 6F",dark=false},
	{name="Ganon's Tower 6F",dark=false},
	{name="Ice Palace B2F",dark=false},
	{name="Ice Palace B6F",dark=false},
	{name="Hyrule Castle 1F",dark=false},
	{name="Hyrule Castle 2F",dark=false},
	{name="Hyrule Castle 1F",dark=false},
	{name="Desert Palace 2F",dark=false},
	{name="Swamp Palace 1F",dark=false},
	{name="Uncle's Resting Place",dark=true},
	{name="Skull Woods 1F",dark=false},
	{name="Skull Woods 1F",dark=false},
	{name="Skull Woods 1F",dark=false},
	{name="Skull Woods 1F",dark=false},
	{name="Ganon's Pet - KING HELMASAUR",dark=false},
	{name="Ganon's Tower 3F",dark=false},
	{name="Ganon's Tower 3F",dark=false},
	{name="Ganon's Tower 4F",dark=false},
	{name="Ice Palace B3F",dark=false},
	{name="Ice Palace B3F",dark=false},
	{name="Hyrule Castle (West Entrance Room)",dark=false},
	{name="Hyrule Castle (Main Entrance Room)",dark=false},
	{name="Hyrule Castle (East Entrance Room)",dark=false},
	{name="Desert Palace (Boss Entrance Room)",dark=false},
	{name="Thieves' Town 1F",dark=false},
	{name="Thieves' Town 1F",dark=false},
	{name="Swamp Palace B2F",dark=false},
	{name="Skull Woods 1F",dark=false},
	{name="Skull Woods 1F",dark=false},
	{name="Empty Clone Room",dark=true},
	{name="Palace of Darkness B1F",dark=true},
	{name="Ganon's Tower 3F",dark=false},
	{name="Ganon's Tower 4F",dark=false},
	{name="Ganon's Tower 4F",dark=false},
	{name="Ice Palace B3F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Hyrule Castle B2F",dark=false},
	{name="Hyrule Castle B1F",dark=false},
	{name="Hyrule Castle B1F",dark=false},
	{name="Desert Palace 1F",dark=false},
	{name="Desert Palace 1F",dark=false},
	{name="Desert Palace 1F",dark=false},
	{name="Swamp Palace B2F",dark=false},
	{name="Tower of Hera 2F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Ganon's Tower 1F",dark=false},
	{name="Ganon's Tower 1F",dark=false},
	{name="Ganon's Tower 1F",dark=false},
	{name="Ice Palace B4F",dark=false},
	{name="Ice Palace B4F",dark=false},
	{name="Hyrule Castle B3F",dark=false},
	{name="Hyrule Castle B2F",dark=false},
	{name="Hyrule Castle B2F",dark=false},
	{name="Desert Palace (West Entrance Room)",dark=false},
	{name="Desert Palace (Main Entrance Room)",dark=false},
	{name="Desert Palace (East Entrance Room)",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Tower of Hera 1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Eastern Palace 1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Ganon's Tower 1F",dark=false},
	{name="Ganon's Tower 1F",dark=false},
	{name="Ganon's Tower 1F",dark=false},
	{name="Ice Palace B4F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Miserable Pile - VITREOUS",dark=false},
	{name="Misery Mire B2F",dark=false},
	{name="Misery Mire B2F",dark=true},
	{name="Misery Mire B2F",dark=true},
	{name="Empty Clone Room",dark=false},
	{name="Ganon's Tower 5F",dark=false},
	{name="Ganon's Tower 5F",dark=false},
	{name="Misery Mire 1F",dark=false},
	{name="Misery Mire 1F",dark=false},
	{name="Eastern Palace 1F",dark=true},
	{name="Empty Clone Room",dark=false},
	{name="Ganon's Tower 1F",dark=false},
	{name="Ganon's Tower 1F",dark=false},
	{name="Ganon's Tower 1F",dark=false},
	{name="Ice Palace B5F",dark=false},
	{name="Ice Palace B5F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Polar Chimaera - TRINEXX",dark=false},
	{name="Ganon's Tower 5F",dark=false},
	{name="Ganon's Tower 5F",dark=false},
	{name="Tower of Hera 1F",dark=false},
	{name="Eastern Palace 1F",dark=false},
	{name="Eastern Palace 1F",dark=false},
	{name="Eastern Palace 1F",dark=false},
	{name="Thieves' Town B1F",dark=false},
	{name="Unflinching Gaze - BLIND",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Ice Palace B5F",dark=false},
	{name="Ice Palace B5F",dark=false},
	{name="Agahnim's Tower 5F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Turtle Rock B3F",dark=false},
	{name="Turtle Rock B2F",dark=true},
	{name="Turtle Rock 1F",dark=false},
	{name="Turtle Rock 1F",dark=false},
	{name="Eastern Palace 1F",dark=false},
	{name="Eastern Palace 1F",dark=false},
	{name="Eastern Palace 1F",dark=true},
	{name="Thieves' Town B1F",dark=false},
	{name="Thieves' Town B1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Ice Palace B6F",dark=false},
	{name="Ice Palace B6F",dark=false},
	{name="Agahnim's Tower 4F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Turtle Rock B2F",dark=false},
	{name="Turtle Rock B2F",dark=false},
	{name="Turtle Rock 1F",dark=false},
	{name="Turtle Rock 1F",dark=false},
	{name="Palace Guardians - ARMOS KNIGHTS",dark=false},
	{name="Eastern Palace 1F",dark=false},
	{name="Nearly Empty Clone Room",dark=false},
	{name="Thieves' Town B1F",dark=false},
	{name="Thieves' Town B1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Ice Palace B6F",dark=false},
	{name="Empty Clone Room",dark=true},
	{name="Agahnim's Tower 4F",dark=true},
	{name="Misery Mire B1F",dark=false},
	{name="Misery Mire B1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Turtle Rock (Laser Bridge)",dark=false},
	{name="Turtle Rock 1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Eastern Palace 2F",dark=false},
	{name="Eastern Palace 2F",dark=false},
	{name="Eastern Palace 2F",dark=false},
	{name="Thieves' Town B1F",dark=false},
	{name="Thieves' Town B1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Entombed Demon - KHOLDSTARE",dark=false},
	{name="Paradox Cave 3F",dark=false},
	{name="Agahnim's Tower 2F",dark=false},
	{name="Forest Thieves' Hideout",dark=false},
	{name="Lumberjack Tree",dark=false},
	{name="Slumbering Bat",dark=false},
	{name="Old Man's Dwelling (Front)",dark=false},
	{name="Old Man's Dwelling (Back)",dark=true},
	{name="Death Mountain Descent (Exit)",dark=true},
	{name="Death Mountain Descent (Entrance)",dark=true},
	{name="Super Bunny Cave 2F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Spectacle Rock Cave (Check)",dark=false},
	{name="Bumper Cave 2F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Ascent Fairy Spring 2F",dark=false},
	{name="Spiral Cave 2F",dark=false},
	{name="Paradox Cave 2F",dark=false},
	{name="Death Mountain Ascent (Entrance)",dark=true},
	{name="Death Mountain Ascent (Exit)",dark=true},
	{name="Sahasrahla's House (West)",dark=false},
	{name="Sahasrahla's House (East)",dark=false},
	{name="Cool Angry Bros (West)",dark=false},
	{name="Cool Angry Bros (East)",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Super Bunny Cave 1F",dark=false},
	{name="Spectacle Rock Cave (Exit)",dark=false},
	{name="Spectacle Rock Cave (Entrance)",dark=false},
	{name="Bumper Cave 1F",dark=false},
	{name="Empty Clone Room",dark=false},
	{name="Ascent Fairy Spring 1F",dark=false},
	{name="Spiral Cave 1F",dark=false},
	{name="Paradox Cave 1F",dark=false},	
	{name="Forest Gambling",dark=false},
	{name="Snitch House",dark=false},
	{name="Sick Boy's House",dark=false},
	{name="Tavern / Shrub Hut",dark=false},
	{name="Link's House",dark=false},
	{name="Sahasrahla's Hideout",dark=false},
	{name="Outcasts Gambling / Brewery",dark=false},
	{name="Library / Warehouse",dark=false},
	{name="Chicken Coop",dark=false},
	{name="Potion Shop",dark=false},
	{name="Aginah's Cave",dark=false},
	{name="The Dam",dark=false},
	{name="Mimic Cave / Hookshot Fairy Spring",dark=false},
	{name="Mire Shed",dark=false},
	{name="Cool Story Bro",dark=false},
	{name="Shop With Carpet",dark=false},
	{name="Shop With Water",dark=false},
	{name="Shooting Gallery",dark=false},
	{name="Cool Story Bro / Shop",dark=false},
	{name="King's Tomb",dark=false},
	{name="Waterfall Well of Wishes / Cool Story Bomb",dark=false},
	{name="Island Well of Wishes / Fairy Fountain",dark=false},
	{name="Pyramid Well of Wishes",dark=false},
	{name="Spike Cave",dark=false},
	{name="Kakariko Gambling",dark=false},
	{name="Blind's Hut 1F",dark=false},
	{name="Cool Story Shrub",dark=false},
	{name="Haunted Grove Overlook / Graveyard Overlook",dark=false},
	{name="Bomb Shop / Seahouse",dark=false},
	{name="Blind's Hut B1F",dark=false},
	{name="Long Fairy Spring / Hype Cave",dark=false},
	{name="Lumberjack House / Shop",dark=false},
	{name="Ice Rod Cave / Good Bee Cave",dark=false},
	{name="Blacksmiths",dark=false},
	{name="Fortune Teller",dark=false},
	{name="Minidorm Cave",dark=false},
	{name="Cool Story Fifty / Bonk Rocks",dark=false},
	{name="Cool Story Twenty / Cool Story Spikes",dark=false},
	{name="Fairy Spring / Checkerboard Cave",dark=false},
	{name="Peg Cave / Cool Story Spikes",dark=false}
}

OverworldList = {
[0]=[[Lost Woods]],
	[[Lost Woods]],
	[[Lumberjacks]],
	[[West Death Mountain]],
	[[West Death Mountain]],
	[[East Death Mountain]],
	[[East Death Mountain]],
	[[Turtle Rock Portal]],
	[[Lost Woods]],
	[[Lost Woods]],
	[[Death Mountain Ascent]],
	[[West Death Mountain]],
	[[West Death Mountain]],
	[[East Death Mountain]],
	[[East Death Mountain]],
	[[Waterfall]],
	[[Kakariko Portal]],
	[[Kakariko Fortune]],
	[[West of Sanctuary]],
	[[Sanctuary]],
	[[Graveyard]],
	[[Riverbend]],
	[[Potion Shop]],
	[[South of Waterfall]],
	[[Kakariko Village]],
	[[Kakariko Village]],
	[[West of Hyrule Castle]],
	[[Hyrule Castle]],
	[[Hyrule Castle]],
	[[River Crossing]],
	[[Eastern Palace]],
	[[Eastern Palace]],
	[[Kakariko Village]],
	[[Kakariko Village]],
	[[Blacksmiths]],
	[[Hyrule Castle]],
	[[Hyrule Castle]],
	[[East of Hyrule Castle]],
	[[Eastern Palace]],
	[[Eastern Palace]],
	[[Fifteen Second Race]],
	[[South of Kakariko]],
	[[Haunted Grove]],
	[[West of Link's House]],
	[[Link's House]],
	[[East of Link's House]],
	[[South of Eastern Palace]],
	[[Eastern Palace Warp]],
	[[Desert of Mystery]],
	[[Desert of Mystery]],
	[[South of Haunted Grove]],
	[[Great Swamp - Northwest]],
	[[Great Swamp - Northeast]],
	[[Lake Hylia]],
	[[Lake Hylia]],
	[[Crab Cove]],
	[[Desert of Mystery]],
	[[Desert of Mystery]],
	[[East of the Desert]],
	[[Great Swamp - Southwest]],
	[[Great Swamp - Southeast]],
	[[Lake Hylia]],
	[[Lake Hylia]],
	[[South of Crab Cove]],
	[[Skeleton Forest]],
	[[Skeleton Forest]],
	[[East of Skeleton Forest]],
	[[West Dark Death Mountain]],
	[[West Dark Death Mountain]],
	[[East Dark Death Mountain]],
	[[East Dark Death Mountain]],
	[[Turtle Rock]],
	[[Skeleton Forest]],
	[[Skeleton Forest]],
	[[Road To Nowhere]],
	[[West Dark Death Mountain]],
	[[West Dark Death Mountain]],
	[[East Dark Death Mountain]],
	[[East Dark Death Mountain]],
	[[Catfish's Waterfall]],
	[[South of Skeleton Forest]],
	[[Outcast Fortune]],
	[[North of Shield Shop]],
	[[West of Bush Maze]],
	[[Bush Maze]],
	[[Dark Riverbend]],
	[[Upper Dark River]],
	[[South of Catfish's Waterfall]],
	[[Village of Outcasts]],
	[[Village of Outcasts]],
	[[Shield Shop]],
	[[Golden Pyramid]],
	[[Golden Pyramid]],
	[[Hookshot Point]],
	[[Palace of Darkness]],
	[[Palace of Darkness]],
	[[Village of Outcasts]],
	[[Village of Outcasts]],
	[[The Broken House]],
	[[Golden Pyramid]],
	[[Golden Pyramid]],
	[[East of the Pyramid]],
	[[Palace of Darkness]],
	[[Palace of Darkness]],
	[[Digging Game]],
	[[South of Village of Outcasts]],
	[[Mourning Grove]],
	[[West of Bomb Shop]],
	[[Bomb Shop]],
	[[East of Bomb Shop]],
	[[South of Palace of Darkness]],
	[[South of Palace of Darkness]],
	[[Swamp of Evil]],
	[[Swamp of Evil]],
	[[South of Mourning Grove]],
	[[Plains of Ruin - Northwest]],
	[[Plains of Ruin - Northeast]],
	[[Lake Demise]],
	[[Lake Demise]],
	[[Devil's Cove]],
	[[Swamp of Evil]],
	[[Swamp of Evil]],
	[[Wall of Containment]],
	[[Plains of Ruin - Southwest]],
	[[Plains of Ruin - Southeast]],
	[[Lake Demise]],
	[[Lake Demise]],
	[[South of Devil's Cove]],
	[[Master Sword Pedestal / Hobo's Bridge]],
	[[Zora's Domain]]
}
